### ISSUE TITLE
Please allow passing canvas styles for spectrum analyser

### ISSUE THREAD

**Issue by santhoshtr** [Lorti/vue-dictaphone#9]
It will be helpful to customize the spectrum analyser using passed styles. For example setting the fillstyle will help setting a desired color to match the background of application. This may be additional properties for the SpectrumAnalyser component along with width height properties.

Setting them to canvas should be easy with its context api

```
canvasContext.strokeStyle = passedStryle
canvasContext.filStyle = '#fff'
```

**Comment by Lorti** [comment]
Hi @santhoshtr, do you want to open a pull request for this feature?

You could change the [SpectrumAnalyser.vue](https://github.com/Lorti/vue-dictaphone/blob/master/src/components/SpectrumAnalyser.vue) component, so that it accepts a custom rendering function as property. This way you could do whatever you’d like with the calculated points.

**Comment by Lorti** [comment]
Thanks!
https://www.npmjs.com/package/vue-dictaphone/v/1.3.0
